#!/bin/bash

#Doing default commands in linux/shell scripting

date

x=$(date +%F)
y=$(date +%d)
z=$(date +%m)
a=$(date +%M)
b=$(date +%h)
c=$(date +%H)
d=$(date +%I)
e=$(date +%D)
f=$(date +%y)
g=$(date +%Y)
echo "Today's date in another format: $x"

echo "$y $z $a $b $c $d $e $f $g"

