#!/bin/bash
#######################
#calculating sum of numbers with arguments at run time
##and then comparing with first number

####################

Number1=$1
Number2=$2
x=(($Number1 + $Number2))
echo "Sum of $Number1 and $Number2 is: $x"