#!/bin/bash

#Practicing sum, deletion, multiplication and division

#Addition:
Number1=$1
Number2=$2

x=$(($Number1+$Number2))

echo "Sum of provided numbers, $Number1 and $Number2 is : $x"

#check condition
check(){
    if [ $Number1 -gt $Number2 ]
    then
    echo "number1 is greater than number2"
    else
    continue
    fi
}

#Deletion:
check()
y=$(($Number1-$Number2))
echo "Removing $Number1 from $Number2, result is: $y"

z=$(($Number2-$Number1))
echo "Removing $Number2 from $Number1, result is: $z"


#Multiplication:
a=$(($Number1*$Number2))
echo " Multiplying the $Number1 with $Number2, result is: $a"

#Division:
check()
b=$(($Number1/$Number2))
echo " Dividing the $Number1 with $Number2, result is: $b"
c=$(($Number2/$Number1))
echo " Dividing the $Number2 with $Number1, result is: $c"





