#!/bin/bash

# we are checking the below in sequence
# either script has root access or not?
# if yes proceed next by checking git installed or not
# if not installed, giving command to install it
# after installing need to check again, whether it is installed or not.

# in the same way need to check whether mysql is installed or not
# if installed print as mysql is already installed, nothing to do further.

R="\e[31m"
G="\e[32m"
Y="\e[33m"
N="\e[0m"

userid=$(id -u)

if [ $userid -ne 0 ]
then
echo " You are not having root access, pls provide root access"
exit 1
else
echo "You can proceed next as you are having the root access"
fi

dnf list installed git

if [ $? -ne 0 ]
  then
      echo "git is not installed, pls install it"

      dnf install git -y
      if [ $? -ne 0 ]
         then
            echo "still has some isssue in installing git, please check it with priority before proceeding to next"
            exit 1
      else
          echo "$G Success...$N Hurray! your service git is installed successfully without any issues... $N"
      fi
  else
  echo "Git is already installed, nothing to do"

fi


dnf list installed mysql

if [ $? -ne 0 ]
  then
      echo "$R Error $N mysql is not installed, pls install it"

      dnf install mysql -y
      if [ $? -ne 0 ]
         then
            echo "still has some isssue in installing mysql, please check it with priority before proceeding to next"
            exit 1
      else
          echo "$Y Hurray! $N your service mysql is installed successfully without any issues"
      fi
  else
  echo "mysql is already installed, nothing to do"

fi