#!/bin/bash
#Printing even numbers till 10


echo "Please enter the number"
read number
echo "Your entered number is : $number"

echo "Below are the even numbers till $number"
for ((i=1 ; i<=$number ; i++))
do
    if [ $((i%2)) == 0 ]
    then
        echo "Even number is : $i"
    fi
done
