#!/bin/bash

#using set -e so that when the script fails at any line, it stops executing at that line itself
set -e

Y="\e[32m"
N="\e[0m"

failed(){
    echo -e "$Y script stopped as failed at $1:$2 $N"
    
}

trap 'failed "$LINENO" "$BASH_COMMAND" ' ERR

echo "Hi ra"

echo hello

echoo "gaaf"

echo hello

#If you run this script, as you used trap command, at line 20, it will stop as command name is wrong and wont proceed to the next line 22



